package main

import (
	"bufio"
	"crypto/tls"
	"crypto/x509"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"log"
	"math/rand"
	"net"
	"net/http"
	"net/url"
	"os"
	"path/filepath"
	"strings"
	"sync"
	"time"

	"github.com/charmbracelet/huh"
	"github.com/gorilla/websocket"
	"github.com/hashicorp/yamux"
)

type Config struct {
	GatewayURL string `json:"gateway_url"`
	Token      string `json:"token"`
	CACertPath string `json:"ca_cert_path,omitempty"` // path to CA cert, required when using wss://
}

func configPath() string {
	home, _ := os.UserHomeDir()
	return filepath.Join(home, ".ambush", "exitnode.json")
}

func loadConfig() (*Config, error) {
	data, err := os.ReadFile(configPath())
	if err != nil {
		return nil, err
	}
	var cfg Config
	if err := json.Unmarshal(data, &cfg); err != nil {
		return nil, err
	}
	if cfg.Token == "" {
		return nil, errors.New("config missing token")
	}
	return &cfg, nil
}

func saveConfig(cfg *Config) error {
	path := configPath()
	if err := os.MkdirAll(filepath.Dir(path), 0700); err != nil {
		return err
	}
	data, err := json.MarshalIndent(cfg, "", "  ")
	if err != nil {
		return err
	}
	return os.WriteFile(path, data, 0600)
}

func defaultCACertPath() string {
	home, _ := os.UserHomeDir()
	return filepath.Join(home, ".ambush", "ca.crt")
}

func runSetup() (*Config, error) {
	cfg := &Config{
		GatewayURL: "ws://localhost:8080",
		CACertPath: defaultCACertPath(),
	}

	err := huh.NewForm(
		huh.NewGroup(
			huh.NewInput().
				Title("Gateway URL").
				Description("Use wss:// for TLS (recommended for production)").
				Placeholder("ws://localhost:8080").
				Value(&cfg.GatewayURL),
			huh.NewInput().
				Title("Token").
				Placeholder("paste your exit node token").
				EchoMode(huh.EchoModePassword).
				Validate(func(s string) error {
					if strings.TrimSpace(s) == "" {
						return errors.New("token cannot be empty")
					}
					return nil
				}).
				Value(&cfg.Token),
			huh.NewInput().
				Title("CA Cert Path").
				Description("Path to ca.crt — required when using wss://").
				Placeholder(defaultCACertPath()).
				Value(&cfg.CACertPath),
		),
	).WithTheme(huh.ThemeCatppuccin()).Run()
	if err != nil {
		return nil, err
	}

	cfg.Token = strings.TrimSpace(cfg.Token)
	cfg.CACertPath = strings.TrimSpace(cfg.CACertPath)

	if err := saveConfig(cfg); err != nil {
		return nil, fmt.Errorf("failed to save config: %w", err)
	}

	fmt.Println("Config saved to", configPath())
	return cfg, nil
}

func configFromEnv() *Config {
	gwURL := os.Getenv("AMBUSH_GATEWAY_URL")
	token := os.Getenv("AMBUSH_TOKEN")
	if gwURL == "" || token == "" {
		return nil
	}
	return &Config{GatewayURL: gwURL, Token: token}
}

func main() {
	cfg := configFromEnv()
	if cfg == nil {
		var err error
		cfg, err = loadConfig()
		if err != nil {
			cfg, err = runSetup()
			if err != nil {
				log.Fatal(err)
			}
		}
	}

	log.Printf("connecting to %s", cfg.GatewayURL)
	const (
		backoffMin = 1 * time.Second
		backoffMax = 60 * time.Second
	)
	delay := backoffMin
	for {
		err := connect(cfg)
		if err == nil {
			// clean disconnect — reset backoff and reconnect quickly
			delay = backoffMin
			continue
		}
		jitter := time.Duration(rand.Int63n(int64(delay / 2)))
		log.Printf("connection lost: %v — retrying in %s", err, (delay + jitter).Round(time.Millisecond))
		time.Sleep(delay + jitter)
		if delay < backoffMax {
			delay *= 2
			if delay > backoffMax {
				delay = backoffMax
			}
		}
	}
}

func buildTLSConfig(cfg *Config) (*tls.Config, error) {
	var caPEM []byte
	if raw := os.Getenv("AMBUSH_CA_CERT"); raw != "" {
		caPEM = []byte(raw)
	} else if cfg.CACertPath != "" {
		var err error
		caPEM, err = os.ReadFile(cfg.CACertPath)
		if err != nil {
			return nil, fmt.Errorf("read CA cert %s: %w", cfg.CACertPath, err)
		}
	} else {
		return nil, errors.New("wss:// requires a CA cert — set CACertPath in config or AMBUSH_CA_CERT env var")
	}

	pool := x509.NewCertPool()
	if !pool.AppendCertsFromPEM(caPEM) {
		return nil, errors.New("CA cert PEM is invalid or empty")
	}

	// ServerName matches the fixed CN in the gateway cert generated by gencerts.
	// This allows the cert to work regardless of the gateway's actual IP or hostname.
	return &tls.Config{RootCAs: pool, ServerName: "ambush-gateway"}, nil
}

func connect(cfg *Config) error {
	u, err := url.Parse(cfg.GatewayURL)
	if err != nil {
		return err
	}
	u.Path = "/exitnode"
	q := u.Query()
	q.Set("token", cfg.Token)
	u.RawQuery = q.Encode()

	dialer := websocket.DefaultDialer
	if strings.HasPrefix(cfg.GatewayURL, "wss://") {
		tlsCfg, err := buildTLSConfig(cfg)
		if err != nil {
			return fmt.Errorf("TLS setup: %w", err)
		}
		dialer = &websocket.Dialer{TLSClientConfig: tlsCfg}
	}

	conn, _, err := dialer.Dial(u.String(), http.Header{})
	if err != nil {
		return err
	}
	defer func() { _ = conn.Close() }()

	log.Printf("connected to gateway at %s", u.Host)

	session, err := yamux.Client(&wsConn{conn: conn}, nil)
	if err != nil {
		return err
	}
	defer func() { _ = session.Close() }()

	log.Println("yamux session ready")

	for {
		stream, err := session.Accept()
		if err != nil {
			return err
		}
		go handleStream(stream)
	}
}

const idleTimeout = 2 * time.Minute

// idleConn resets the connection deadline on every read or write,
// closing the connection if idle for longer than timeout.
type idleConn struct {
	net.Conn
	timeout time.Duration
}

func (c *idleConn) Read(b []byte) (int, error) {
	_ = c.Conn.SetDeadline(time.Now().Add(c.timeout))
	return c.Conn.Read(b)
}

func (c *idleConn) Write(b []byte) (int, error) {
	_ = c.Conn.SetDeadline(time.Now().Add(c.timeout))
	return c.Conn.Write(b)
}

func handleStream(stream net.Conn) {
	defer func() { _ = stream.Close() }()

	// Wrap stream before creating the bufio.Reader so deadline is reset
	// on every underlying Read, including buffered ones.
	idleStream := &idleConn{Conn: stream, timeout: idleTimeout}
	_ = stream.SetDeadline(time.Now().Add(idleTimeout))

	br := bufio.NewReader(idleStream)
	line, err := br.ReadString('\n')
	if err != nil {
		log.Printf("stream: failed to read header: %v", err)
		return
	}
	line = strings.TrimSpace(line)

	// Header format: "<req_id> <addr>"
	reqID, addr, ok := strings.Cut(line, " ")
	if !ok {
		log.Printf("stream: malformed header %q", line)
		return
	}

	target, err := net.Dial("tcp", addr)
	if err != nil {
		log.Printf("stream: req=%s dial %s failed: %v", reqID, addr, err)
		return
	}
	defer func() { _ = target.Close() }()
	idleTarget := &idleConn{Conn: target, timeout: idleTimeout}
	_ = target.SetDeadline(time.Now().Add(idleTimeout))

	log.Printf("stream: req=%s relaying to %s", reqID, addr)

	done := make(chan struct{}, 2)
	go func() { _, _ = io.Copy(idleTarget, br); done <- struct{}{} }()
	go func() { _, _ = io.Copy(idleStream, idleTarget); done <- struct{}{} }()
	<-done
}

// wsConn wraps a gorilla WebSocket connection as a net.Conn for yamux.
type wsConn struct {
	conn   *websocket.Conn
	mu     sync.Mutex
	reader io.Reader
}

func (c *wsConn) Read(b []byte) (int, error) {
	for {
		if c.reader != nil {
			n, err := c.reader.Read(b)
			if err == io.EOF {
				c.reader = nil
				continue
			}
			return n, err
		}
		_, r, err := c.conn.NextReader()
		if err != nil {
			return 0, err
		}
		c.reader = r
	}
}

func (c *wsConn) Write(b []byte) (int, error) {
	c.mu.Lock()
	defer c.mu.Unlock()
	if err := c.conn.WriteMessage(websocket.BinaryMessage, b); err != nil {
		return 0, err
	}
	return len(b), nil
}

func (c *wsConn) Close() error                       { return c.conn.Close() }
func (c *wsConn) LocalAddr() net.Addr                { return c.conn.LocalAddr() }
func (c *wsConn) RemoteAddr() net.Addr               { return c.conn.RemoteAddr() }
func (c *wsConn) SetDeadline(t time.Time) error {
	if err := c.conn.SetReadDeadline(t); err != nil {
		return err
	}
	return c.conn.SetWriteDeadline(t)
}
func (c *wsConn) SetReadDeadline(t time.Time) error  { return c.conn.SetReadDeadline(t) }
func (c *wsConn) SetWriteDeadline(t time.Time) error { return c.conn.SetWriteDeadline(t) }
